/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import connection.FornecedoresControl;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinio
 */
public class Fornecedores extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedores
     */
    public Fornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLblButtonMenu = new javax.swing.JLabel();
        jLblButtonEstoque = new javax.swing.JLabel();
        jLblButtonFornecedores = new javax.swing.JLabel();
        jLblButtonFuncionarios = new javax.swing.JLabel();
        jLblButtonVendas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLblButtonAdicionar2 = new javax.swing.JLabel();
        jLblButtonAlterarStatus = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFNomeFornecedor = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFStatus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLblButtonAlterar = new javax.swing.JLabel();
        jLblButtonVisualizar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fornecedores");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanelMenu.setPreferredSize(new java.awt.Dimension(1000, 60));
        jPanelMenu.setLayout(new java.awt.GridLayout(1, 0));

        jLblButtonMenu.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonMenu.setText("Menu");
        jLblButtonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonMenu.setOpaque(true);
        jLblButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonMenuMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonMenu);

        jLblButtonEstoque.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonEstoque.setText("Estoque");
        jLblButtonEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonEstoque.setOpaque(true);
        jLblButtonEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonEstoque);

        jLblButtonFornecedores.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonFornecedores.setText("Fornecedores");
        jLblButtonFornecedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonFornecedores.setOpaque(true);
        jLblButtonFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonFornecedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonFornecedoresMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonFornecedores);

        jLblButtonFuncionarios.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonFuncionarios.setText("Funcionários");
        jLblButtonFuncionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonFuncionarios.setOpaque(true);
        jLblButtonFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonFuncionarios);

        jLblButtonVendas.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonVendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonVendas.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonVendas.setText("Vendas");
        jLblButtonVendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonVendas.setOpaque(true);
        jLblButtonVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonVendas);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tabela de fornecedores.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLblButtonAdicionar2.setBackground(new java.awt.Color(31, 43, 68));
        jLblButtonAdicionar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonAdicionar2.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonAdicionar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonAdicionar2.setText("Adicionar ");
        jLblButtonAdicionar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 133, 196), 2));
        jLblButtonAdicionar2.setOpaque(true);
        jLblButtonAdicionar2.setPreferredSize(new java.awt.Dimension(200, 30));
        jLblButtonAdicionar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonAdicionar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonAdicionar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonAdicionar2MouseExited(evt);
            }
        });

        jLblButtonAlterarStatus.setBackground(new java.awt.Color(31, 43, 68));
        jLblButtonAlterarStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonAlterarStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonAlterarStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonAlterarStatus.setText("Alterar status");
        jLblButtonAlterarStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 133, 196), 2));
        jLblButtonAlterarStatus.setOpaque(true);
        jLblButtonAlterarStatus.setPreferredSize(new java.awt.Dimension(200, 30));
        jLblButtonAlterarStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonAlterarStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonAlterarStatusMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Nome do fornecedor ");

        jTFNomeFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFNomeFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTFNomeFornecedor.setPreferredSize(new java.awt.Dimension(150, 30));

        jTFTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTFTelefone.setPreferredSize(new java.awt.Dimension(150, 30));

        jTFStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTFStatus.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Telefone");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Status");

        jLblButtonAlterar.setBackground(new java.awt.Color(31, 43, 68));
        jLblButtonAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonAlterar.setText("Alterar");
        jLblButtonAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 133, 196), 2));
        jLblButtonAlterar.setOpaque(true);
        jLblButtonAlterar.setPreferredSize(new java.awt.Dimension(200, 30));
        jLblButtonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonAlterarMouseExited(evt);
            }
        });

        jLblButtonVisualizar.setBackground(new java.awt.Color(31, 43, 68));
        jLblButtonVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonVisualizar.setText("Visualizar");
        jLblButtonVisualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 133, 196), 2));
        jLblButtonVisualizar.setOpaque(true);
        jLblButtonVisualizar.setPreferredSize(new java.awt.Dimension(200, 30));
        jLblButtonVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonVisualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonVisualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLblButtonAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLblButtonAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLblButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblButtonAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblButtonAdicionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTFornecedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Status"
            }
        ));
        jTFornecedores.setGridColor(new java.awt.Color(0, 0, 0));
        jTFornecedores.setPreferredSize(new java.awt.Dimension(452, 402));
        jScrollPane1.setViewportView(jTFornecedores);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLblButtonMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonMenuMouseEntered
        // TODO add your handling code here:
        jLblButtonMenu.setBackground(new Color(51, 0, 204));
    }//GEN-LAST:event_jLblButtonMenuMouseEntered

    private void jLblButtonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonMenuMouseExited
        // TODO add your handling code here:
        jLblButtonMenu.setBackground(new Color(38, 133, 196));
    }//GEN-LAST:event_jLblButtonMenuMouseExited

    private void jLblButtonEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseEntered
        // TODO add your handling code here:
        jLblButtonEstoque.setBackground(new Color(51, 0, 204));
    }//GEN-LAST:event_jLblButtonEstoqueMouseEntered

    private void jLblButtonEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseExited
        // TODO add your handling code here:
        jLblButtonEstoque.setBackground(new Color(38, 133, 196));
    }//GEN-LAST:event_jLblButtonEstoqueMouseExited

    private void jLblButtonFornecedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFornecedoresMouseEntered
        // TODO add your handling code here:
        jLblButtonFornecedores.setBackground(new Color(51, 0, 204));
    }//GEN-LAST:event_jLblButtonFornecedoresMouseEntered

    private void jLblButtonFornecedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFornecedoresMouseExited
        // TODO add your handling code here:
        jLblButtonFornecedores.setBackground(new Color(38, 133, 196));
    }//GEN-LAST:event_jLblButtonFornecedoresMouseExited

    private void jLblButtonFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseEntered
        // TODO add your handling code here:
        jLblButtonFuncionarios.setBackground(new Color(51, 0, 204));
    }//GEN-LAST:event_jLblButtonFuncionariosMouseEntered

    private void jLblButtonFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseExited
        // TODO add your handling code here:
        jLblButtonFuncionarios.setBackground(new Color(38, 133, 196));
    }//GEN-LAST:event_jLblButtonFuncionariosMouseExited

    private void jLblButtonVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseEntered
        // TODO add your handling code here:
        jLblButtonVendas.setBackground(new Color(51, 0, 204));
    }//GEN-LAST:event_jLblButtonVendasMouseEntered

    private void jLblButtonVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseExited
        // TODO add your handling code here:
        jLblButtonVendas.setBackground(new Color(38, 133, 196));
    }//GEN-LAST:event_jLblButtonVendasMouseExited

    private void jLblButtonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonMenuMouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonMenuMouseClicked

    private void jLblButtonEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseClicked
        // TODO add your handling code here:
        Estoque estoque = new Estoque();
        estoque.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonEstoqueMouseClicked

    private void jLblButtonFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseClicked
        // TODO add your handling code here:
        Funcionarios funcionarios = new Funcionarios();
        funcionarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonFuncionariosMouseClicked

    private void jLblButtonVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseClicked
        // TODO add your handling code here:
        Vendas vendas = new Vendas();
        vendas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonVendasMouseClicked

    private void jLblButtonAdicionar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAdicionar2MouseEntered
        // TODO add your handling code here:
        jLblButtonAdicionar2.setBackground(new Color(38, 133, 196));
        Border border = BorderFactory.createLineBorder(new Color(31, 43, 68), 2);
        jLblButtonAdicionar2.setBorder(border);
    }//GEN-LAST:event_jLblButtonAdicionar2MouseEntered

    private void jLblButtonAdicionar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAdicionar2MouseExited
        // TODO add your handling code here:
        jLblButtonAdicionar2.setBackground(new Color(31, 43, 68));
        Border border = BorderFactory.createLineBorder(new Color(38, 133, 196), 2);
        jLblButtonAdicionar2.setBorder(border);
    }//GEN-LAST:event_jLblButtonAdicionar2MouseExited

    private void jLblButtonAlterarStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAlterarStatusMouseEntered
        // TODO add your handling code here:
        jLblButtonAlterarStatus.setBackground(new Color(38, 133, 196));
        Border border = BorderFactory.createLineBorder(new Color(31, 43, 68), 2);
        jLblButtonAlterarStatus.setBorder(border);
    }//GEN-LAST:event_jLblButtonAlterarStatusMouseEntered

    private void jLblButtonAlterarStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAlterarStatusMouseExited
        // TODO add your handling code here:
        jLblButtonAlterarStatus.setBackground(new Color(31, 43, 68));
        Border border = BorderFactory.createLineBorder(new Color(38, 133, 196), 2);
        jLblButtonAlterarStatus.setBorder(border);
    }//GEN-LAST:event_jLblButtonAlterarStatusMouseExited

    private void jLblButtonAdicionar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAdicionar2MouseClicked
        FornecedoresControl fornecedores = new FornecedoresControl();

        String nome = jTFNomeFornecedor.getText();
        String telefone = jTFTelefone.getText();
        String status = jTFStatus.getText();

        if (fornecedores.inserirFonecedor(nome, telefone, status) == true) {
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Adicione todas informações sobre um novo fornecedor", "Erro",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLblButtonAdicionar2MouseClicked

    private void jLblButtonAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAlterarMouseEntered
        // TODO add your handling code here:
        jLblButtonAlterar.setBackground(new Color(38, 133, 196));
        Border border = BorderFactory.createLineBorder(new Color(31, 43, 68), 2);
        jLblButtonAlterar.setBorder(border);
    }//GEN-LAST:event_jLblButtonAlterarMouseEntered

    private void jLblButtonAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAlterarMouseExited
        // TODO add your handling code here:
        jLblButtonAlterar.setBackground(new Color(31, 43, 68));
        Border border = BorderFactory.createLineBorder(new Color(38, 133, 196), 2);
        jLblButtonAlterar.setBorder(border);
    }//GEN-LAST:event_jLblButtonAlterarMouseExited

    private void jLblButtonVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVisualizarMouseEntered
        // TODO add your handling code here:
        jLblButtonVisualizar.setBackground(new Color(38, 133, 196));
        Border border = BorderFactory.createLineBorder(new Color(31, 43, 68), 2);
        jLblButtonVisualizar.setBorder(border);
    }//GEN-LAST:event_jLblButtonVisualizarMouseEntered

    private void jLblButtonVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVisualizarMouseExited
        // TODO add your handling code here:
        jLblButtonVisualizar.setBackground(new Color(31, 43, 68));
        Border border = BorderFactory.createLineBorder(new Color(38, 133, 196), 2);
        jLblButtonVisualizar.setBorder(border);
    }//GEN-LAST:event_jLblButtonVisualizarMouseExited

    private void jLblButtonAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonAlterarMouseClicked
        // TODO add your handling code here:
        JDialogFornecedores dialog = new JDialogFornecedores(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLblButtonAlterarMouseClicked

    private void jLblButtonVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVisualizarMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/supramercado", "postgres", "SENHABANCO");

            String sql = "SELECT * FROM fornecedores";
            PreparedStatement pstm = con.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            DefaultTableModel tblModel = (DefaultTableModel) jTFornecedores.getModel();
            tblModel.setRowCount(0);
            
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id"));
                String nome = rs.getString("nome");
                String telefone = rs.getString("telefone");
                String status = rs.getString("status");

                String tbData[] = {id, nome, telefone, status};

                tblModel.addRow(tbData);
            }

            con.close();

        } catch (Exception e) {
            System.out.println("Erro na conexão: " + e);
        }
    }//GEN-LAST:event_jLblButtonVisualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLblButtonAdicionar2;
    private javax.swing.JLabel jLblButtonAlterar;
    private javax.swing.JLabel jLblButtonAlterarStatus;
    private javax.swing.JLabel jLblButtonEstoque;
    private javax.swing.JLabel jLblButtonFornecedores;
    private javax.swing.JLabel jLblButtonFuncionarios;
    private javax.swing.JLabel jLblButtonMenu;
    private javax.swing.JLabel jLblButtonVendas;
    private javax.swing.JLabel jLblButtonVisualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNomeFornecedor;
    private javax.swing.JTextField jTFStatus;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTable jTFornecedores;
    // End of variables declaration//GEN-END:variables
}
