/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.awt.Color;

/**
 *
 * @author vinio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLblButtonMenu = new javax.swing.JLabel();
        jLblButtonEstoque = new javax.swing.JLabel();
        jLblButtonFornecedores = new javax.swing.JLabel();
        jLblButtonFuncionarios = new javax.swing.JLabel();
        jLblButtonVendas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanelMenu.setPreferredSize(new java.awt.Dimension(1000, 60));
        jPanelMenu.setLayout(new java.awt.GridLayout(1, 0));

        jLblButtonMenu.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonMenu.setText("Menu");
        jLblButtonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonMenu.setOpaque(true);
        jLblButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonMenuMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonMenu);

        jLblButtonEstoque.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonEstoque.setText("Estoque");
        jLblButtonEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonEstoque.setOpaque(true);
        jLblButtonEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonEstoqueMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonEstoque);

        jLblButtonFornecedores.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonFornecedores.setText("Fornecedores");
        jLblButtonFornecedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonFornecedores.setOpaque(true);
        jLblButtonFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonFornecedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonFornecedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonFornecedoresMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonFornecedores);

        jLblButtonFuncionarios.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonFuncionarios.setText("Funcionários");
        jLblButtonFuncionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonFuncionarios.setOpaque(true);
        jLblButtonFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonFuncionariosMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonFuncionarios);

        jLblButtonVendas.setBackground(new java.awt.Color(38, 133, 196));
        jLblButtonVendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblButtonVendas.setForeground(new java.awt.Color(255, 255, 255));
        jLblButtonVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblButtonVendas.setText("Vendas");
        jLblButtonVendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 43, 68), 2));
        jLblButtonVendas.setOpaque(true);
        jLblButtonVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblButtonVendasMouseExited(evt);
            }
        });
        jPanelMenu.add(jLblButtonVendas);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLblButtonMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonMenuMouseEntered
        // TODO add your handling code here:
        jLblButtonMenu.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_jLblButtonMenuMouseEntered

    private void jLblButtonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonMenuMouseExited
        // TODO add your handling code here:
        jLblButtonMenu.setBackground(new Color(38,133,196));
    }//GEN-LAST:event_jLblButtonMenuMouseExited

    private void jLblButtonEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseEntered
        // TODO add your handling code here:
        jLblButtonEstoque.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_jLblButtonEstoqueMouseEntered

    private void jLblButtonEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseExited
        // TODO add your handling code here:
        jLblButtonEstoque.setBackground(new Color(38,133,196));
    }//GEN-LAST:event_jLblButtonEstoqueMouseExited

    private void jLblButtonFornecedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFornecedoresMouseEntered
        // TODO add your handling code here:
        jLblButtonFornecedores.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_jLblButtonFornecedoresMouseEntered

    private void jLblButtonFornecedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFornecedoresMouseExited
        // TODO add your handling code here:
        jLblButtonFornecedores.setBackground(new Color(38,133,196));
    }//GEN-LAST:event_jLblButtonFornecedoresMouseExited

    private void jLblButtonFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseEntered
        // TODO add your handling code here:
        jLblButtonFuncionarios.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_jLblButtonFuncionariosMouseEntered

    private void jLblButtonFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseExited
        // TODO add your handling code here:
        jLblButtonFuncionarios.setBackground(new Color(38,133,196));
    }//GEN-LAST:event_jLblButtonFuncionariosMouseExited

    private void jLblButtonVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseEntered
        // TODO add your handling code here:
        jLblButtonVendas.setBackground(new Color(51,0,204));
    }//GEN-LAST:event_jLblButtonVendasMouseEntered

    private void jLblButtonVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseExited
        // TODO add your handling code here:
        jLblButtonVendas.setBackground(new Color(38,133,196));
    }//GEN-LAST:event_jLblButtonVendasMouseExited

    private void jLblButtonEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonEstoqueMouseClicked
        // TODO add your handling code here:
        Estoque estoque = new Estoque(); 
        estoque.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonEstoqueMouseClicked

    private void jLblButtonFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFornecedoresMouseClicked
        // TODO add your handling code here:
        Fornecedores fornecedores = new Fornecedores(); 
        fornecedores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonFornecedoresMouseClicked

    private void jLblButtonFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonFuncionariosMouseClicked
        // TODO add your handling code here:
        Funcionarios funcionarios = new Funcionarios(); 
        funcionarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonFuncionariosMouseClicked

    private void jLblButtonVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblButtonVendasMouseClicked
        // TODO add your handling code here:
        Vendas vendas = new Vendas(); 
        vendas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLblButtonVendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblButtonEstoque;
    private javax.swing.JLabel jLblButtonFornecedores;
    private javax.swing.JLabel jLblButtonFuncionarios;
    private javax.swing.JLabel jLblButtonMenu;
    private javax.swing.JLabel jLblButtonVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
